# Generated by Django 5.1.3 on 2024-12-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0002_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="like",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.CharField(max_length=300),
        ),
    ]
